---
- name: Pull OWASP Juice Shop Docker image
  containers.podman.podman_image:
    name: bkimminich/juice-shop
    source: pull
    state: present

- name: Run OWASP Juice Shop container
  containers.podman.podman_container:
    name: juice-shop
    image: bkimminich/juice-shop
    ports:
      - "3000:3000"
    state: started
    restart_policy: always
