---
- name: Pull OWASP Juice Shop Docker image
  containers.podman.podman_image:
    name: docker.io/bkimminich/juice-shop:latest
    state: present

- name: Run OWASP Juice Shop container
  containers.podman.podman_container:
    name: juice-shop
    image: docker.io/bkimminich/juice-shop:latest
    ports:
      - "3000:3000"
    state: started
    restart_policy: always
